# Generated by Django 3.2.9 on 2021-12-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcollection',
            name='author',
            field=models.TextField(),
        ),
    ]
