# Generated by Django 3.2.9 on 2021-12-05 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
        ('home', '0002_alter_postcollection_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcollection',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.profile'),
        ),
    ]
